### ISSUE TITLE
Schema registry API coverage

### ISSUE THREAD

**Issue by adelbertc** [haskell-works/hw-kafka-avro#13]
So I'm looking at this project because I need Haskell Schema Registry bindings, but the current bindings are missing some endpoints that I would like (e.g. compatibility checks and configs). I am happy to add these myself but was wondering if you would like these additions to this project, which seems to not need those endpoints. If not, then would you be interested in splitting out the schema registry into its own tiny library? Alternatively if you prefer I can just do my own thing. Let me know!

**Comment by AlexeyRaga** [comment]
@adelbertc I think it is a great idea to extend an interface of this library! This project is currently tiny, just `encode` and `decode` functions, really.
We can start adding them here, and if we see that it is growing above itself then we can always split.
