### ISSUE TITLE
Effects and testing

### ISSUE THREAD

**Issue by adelbertc** [haskell-works/hw-kafka-avro#16]
I'm thinking of how to a) structure the package to make it more testable and b) modify the Schema Registry bindings so they are more composable. Currently a) is a bit hard because we are tied to `IO` and would need a mock Schema Registry instance to test, and b) needs some work since the way the functions are structures makes it a bit tricky to compose, e.g. being able to chain several calls and pass in the `SchemaRegistry` instance once at the top.

I tend towards the tagless final/MTL approach - my initial thoughts are either using something like [monad-http](https://hackage.haskell.org/package/monad-http) or doing an equivalent thing in this package ourselves if we want to avoid incurring a dependency. We could then change the public API to use `MonadHttp` and other MTL type classes, e.g.

```haskell
loadSchema :: (MonadHttp m, MonadReader SchemaRegistry m, MonadError SchemaRegistryError m) => SchemaId -> m Schema
```

Then we provide instances for a data type that delegates to `wreq` and in test we can easily mock the HTTP responses as well.

Thoughts?

**Comment by adelbertc** [comment]
Ahh interesting, that is a fair point I confess I had not thought much about. How would you feel about shuffling the argument order so `SchemaRegistry` is the "last" argument then? This would still make it easy to explicitly pass arguments, and also allow use of the `a ->` Reader instance if folks would like. It seems also that is the order your example expects.

**Comment by adelbertc** [comment]
I started looking into monad-http a bit more and also came across [req](https://github.com/mrkkrp/req) - any thoughts on monad-http + wreq vs. req ? There is a comparison (albeit probably a biased one) [here](https://github.com/mrkkrp/req#motivation-and-req-vs-other-libraries).

**Comment by AlexeyRaga** [comment]
I guess having `SchemaRegistry` as a first parameter allows a nice "partial application" scenarios, such as:
```
mapM (decodeWithSchema sr) payloads
```

This one above and `Conduit`'s `.| mapMC (decodeWithSchema sr)` I use pretty much everywhere. If we make `SchemaRegistry` to be the last parameter at least these calls will look noisier.

I  think it is a common practice in Haskell to put parameters that are less likely to vary at the beginning to make partial application easier.


Is there a particular problem we are trying to solve by re-arranging parameters?

**Comment by adelbertc** [comment]
My use case is I want to be able to talk about Schema Registry operations and not have to pass in the location until the "end of the world," something like:

```haskell
compatibleWithLatest :: Subject -> Schema -> SchemaRegistry -> ExceptT SchemaRegistryError IO Bool
compatibleWithLatest subject schema = do
  versions <- getVersions subject
  let latest = last versions
  latestSchema <- loadSubjectSchema subject latest
  isCompatible subject latest schema
```

Basically by putting the `SchemaRegistry` parameter last I can use it in a Reader monad style, and can even make the surface look a bit nicer with like `type SchemaRegistry a = SchemaRegistry -> ExceptT SchemaRegistryErro IO a`.

Also separately any thoughts on https://github.com/haskell-works/hw-kafka-avro/issues/16#issuecomment-401568491 ?

**Comment by jkachmar** [comment]
The downside with the scrap-your-typeclases approach is you end up using existentials like this:
```haskell
data SchemaRegistry = SchemaRegistry
  { srCache        :: Cache SchemaId Schema
  , srReverseCache :: Cache (Subject, SchemaName) SchemaId
  , srBaseUrl      :: String

  -- this is new, can be a separate record
  , srRestGet      :: forall a. FromJSON a => Url -> IO (Maybe a)
  , srRestPost     :: forall a b. (FromJSON a, ToJSON b) => Url -> b -> IO (Maybe a)
  }
```
...at which point I think you're just better off making it a typeclass.

Have you seen [Matt Parsons' blog post on structuring effects in a Haskell application](http://www.parsonsmatt.org/2018/03/22/three_layer_haskell_cake.html)?

It feels like there's something here that could be pulled out into a typeclass that handles data fetch events (i.e. much more constrained than something like `MonadRest` or `MonadHTTP`), but I'm not sure how it could be done without "infecting" the library with some transformer that the user would need to run.

cf. https://github.com/bitemyapp/bloodhound/blob/c71a130f1f02ad905697f859cfb33c154df6455f/src/Database/V5/Bloodhound/Internal/Client.hs#L49 for possible inspiration

**Comment by AlexeyRaga** [comment]
Yes, I've seen Matt's post and I myself use this approach. I am not entirely happy with it though for a couple of reasons, and I am now seriously considering trying the "scrap" approach for my next service. I haven't tried it though.

I also have a couple of my own monads similar to `MonadBH` you are referring too.
The problem with this approach is that these classes do not describe operations, but at the same time require providing an environment (`getBHEnv :: m BHEnv`). Which means that even for unit tests I need to provide it with an HTTP client manager...

But again, as I said in https://github.com/haskell-works/hw-kafka-avro/issues/16#issuecomment-401002440, I am OK with using type classes approach, whether is `MonadHttp` or something like that `MonadRest`. 
I am not sure what is the best way to expose it to clients. I _currently_ don't think that clients should be concerned with these monads and that simply exposing `IO (Either  ...)` is most convenient... But I am not coming from the "non-algebraic and lawless type classes must not be created" clan, so I am fine with using classes :)
