### ISSUE TITLE
Schemas aren't cached

### ISSUE THREAD

**Issue by torgeirsh** [haskell-works/hw-kafka-avro#28]
decodeWithSchema calls loadSchema, which looks up the schema in the cache, and if it doesn't find it, calls getSchemaById, which downloads the schema from the registry. However, I can't see that the downloaded schema is stored in the cache. With Wireshark running, I can see that the schema is downloaded every time a Kafka message is decoded, so it takes a long time to process 5000 messages. Is this a bug, or am I using the library the wrong way?

**Comment by AlexeyRaga** [comment]
@torgeirsh Wow, you are right! `loadSubjectSchema` does cache schemas, but not `loadSchema`.
It is certainly a bug.
