### ISSUE TITLE
Exceptions when encoding

### ISSUE THREAD

**Issue by torgeirsh** [haskell-works/hw-kafka-avro#42]
encodeValue throws exceptions on schema registry connection errors instead of using the SchemaRegistryConnectError constructor for the returned error. Is that intended behaviour? I haven't tried the other encode functions, but I assume they behave in the same way.

**Comment by AlexeyRaga** [comment]
No, it is not intended, must be a bug.
Perhaps the root cause would be around here? https://github.com/haskell-works/hw-kafka-avro/blob/master/src/Kafka/Avro/SchemaRegistry.hs#L197
